/**
 * PlaidButton.jsx
 * ----------------
 * Renders a custom-styled "Connect a bank account" button (MUI) that launches Plaid Link
 * via the `usePlaidLink` hook. After the user finishes linking, we immediately normalize 
 * the returned recurring data, then bubble it up via `onData(items)` so the parent page 
 * can render the subscriptions list.
 *
 * Notes:
 * - We hide the button while loading and show a spinner loader.
 * - `ready` from the hook indicates when Plaid is initialized and safe to open.
 * - We don't modify the parent's state directly—everything goes through `onData`.
 */

import React, { useState } from "react";
import { usePlaidLink } from "react-plaid-link";
import Button from "@mui/material/Button";
import AccountBalanceRoundedIcon from "@mui/icons-material/AccountBalanceRounded";
import { toRecurringItems } from "../utils/recurring-data-formatter";


/**
 * Exchange endpoint (server or Pipedream) that receives the public_token,
 * exchanges it plaid for an access token which is subsequently used to
 * retrieve the recurring subscriptions
 */
const EXCHANGE_URL = process.env.REACT_APP_ACCESS_TOKEN_RECURRING_TRANSACTIONS_TRIGGER;

// Lightweight inline spinner. We keep it minimal and accessible
const Loader = () => (
    <div style={{ display: "flex", justifyContent: "center", padding: "40px 0" }}>
        <div
            style={{
                width: 28,
                height: 28,
                border: "3px solid #c7eadb",
                borderTopColor: "#0a6b3d",
                borderRadius: "50%",
                animation: "spin 0.8s linear infinite",
            }}
            aria-label="Loading"
            role="status"
        />
        <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
);

export default function PlaidButton({ linkToken, onData, userId }) {
    // Local UI state for inline feedback
    const [message, setMessage] = useState(null);
    const [isError, setIsError] = useState(false);
    const [loading, setLoading] = useState(false);

    /**
     * usePlaidLink hook
     * - `token`: short-lived link_token generated by pipedream; required to open Link.
     * - `open()`: function to launch Plaid Link from our custom button.
     * - `ready`: boolean indicating the Link SDK is initialized and can be opened.
     * - `error`: initialization error (if any).
     * - `onSuccess`: callback fired when user completes Link successfully; receives `public_token`.
     */
    const { open, ready, error } = usePlaidLink({
        token: linkToken,
        onSuccess: async (public_token) => {
            // Resolve user id from prop first, fallback to localStorage (if present)
            const uid = userId ?? localStorage.getItem("user_id");
            setLoading(true);
            setIsError(false);
            setMessage(null);

            try {
                // Exchange the short-lived public_token *immediately* on the backend.
                // The backend should return recurring_data (already aggregated/normalized or raw).
                const res = await fetch(EXCHANGE_URL, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ publicToken: public_token, userId: uid }),
                });
                if (!res.ok) throw new Error(`HTTP error! Status: ${res.status}`);

                const data = await res.json();

                // Convert backend payload into the shape expected by the UI cards.
                const items = await toRecurringItems(data?.response_object?.data);

                // Immediately bubble the data up so LinkPage can render <Subscriptions/>
                onData?.(items);
            } catch (e) {
                // Surface a user-friendly error and return an empty list to the parent
                console.error(e);
                setIsError(true);
                setMessage("There was an error retrieving recurring transactions.");
                onData?.([]);
            } finally {
                setLoading(false);
            }
        },
    });

    return (
        // `aria-busy` signals to assistive tech that content is updating
        <div style={{ textAlign: "center" }} aria-busy={loading}>
            {/* While loading, hide the CTA and show the spinner */}
            {loading ? (
                <Loader />
            ) : (
                <>
                    {/* Intro panel: provides context so the page isn’t just a button */}
                    <div
                        style={{
                            maxWidth: 720,
                            margin: "0 auto 24px",
                            textAlign: "center",
                            padding: "16px 20px",
                            background: "linear-gradient(180deg,#f8fbff 0%, #f3f6ff 100%)",
                            border: "1px solid #e6edff",
                            borderRadius: 12,
                            boxShadow: "0 1px 2px rgba(15,23,42,0.06)",
                        }}
                    >
                        <p
                            style={{
                                margin: 0,
                                color: "#334155",
                                fontSize: 16,
                                lineHeight: 1.6,
                            }}
                        >
                            Connect your bank to securely scan recent transactions and identify recurring
                            charges and subscriptions. <strong>We use read-only access via Plaid</strong>—no
                            money moves and your credentials aren’t stored. After the scan, you’ll see each
                            subscription’s amount, frequency, and next charge so you can review or cancel
                            what you don’t need.
                        </p>
                    </div>

                    {/* Custom-styled MUI button; `open()` launches Plaid Link when `ready` is true */}
                    <Button
                        variant="contained"
                        size="large"
                        startIcon={<AccountBalanceRoundedIcon />}
                        onClick={() => open()}
                        disabled={!ready} // disable until Link SDK is initialized
                        sx={{
                            px: 3,
                            py: 1,
                            borderRadius: "999px",
                            fontWeight: 700,
                            textTransform: "none",
                        }}
                    >
                        Connect a bank account
                    </Button>
                </>
            )}

            {/* Inline status message (shown only when not loading) */}
            {!loading && message && (
                <div
                    style={{
                        marginTop: 20,
                        padding: "12px 14px",
                        borderRadius: 8,
                        backgroundColor: isError ? "#ffe0e0" : "#e7f7ee",
                        color: isError ? "#a00000" : "#0a6b3d",
                        fontWeight: 600,
                        maxWidth: 640,
                        marginInline: "auto",
                    }}
                >
                    {message}
                </div>
            )}

            {/* Initialization error from the Plaid Link hook (not the exchange flow) */}
            {error && !loading && (
                <div style={{ marginTop: 8, color: "#a00000", fontSize: 12 }}>
                    Couldn’t initialize Plaid Link. Please refresh and try again.
                </div>
            )}
        </div>
    );
}
